ci:
  autoupdate_schedule: quarterly

default_install_hook_types:
  - pre-commit

default_language_version:
  python: python3.11

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-json
    - id: check-toml
    - id: check-added-large-files
    - id: check-case-conflict

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.37.4
  hooks:
    - id: check-dependabot
    - id: check-github-workflows
      args: ["--verbose"]

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 26.5.1
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.20
  hooks:
  - id: ruff
    args: [ --fix ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.2
  hooks:
  - id: codespell
    additional_dependencies:
    - tomli

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v2.1.0
  hooks:
  - id: mypy
